# Generated by Django 5.0.2 on 2024-03-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator_conversation_id', models.CharField(max_length=100)),
                ('initiator_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party_a', models.CharField(max_length=100)),
                ('party_b', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('occasion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='B2BTransaction',
        ),
    ]
